### ISSUE TITLE
日志记录线程这些原子性的操作不是很明白，可以解释下吗？

### ISSUE THREAD

**Issue by QuanWenLan** [niumoo/down-bit#1]
![image](https://user-images.githubusercontent.com/38965675/89272336-930ceb00-d670-11ea-94de-0b3d8a2e611f.png)

**Comment by niumoo** [comment]
这个实现时还是比较粗糙的，性能也不够友好。基本逻辑是：
A 线程每个线程向日志线程发送已经下载的字节大小
B 线程每个线程向日志线程发送已经下载的字节大小
......
A B 线程不断下载，保证日志线程里记录的一直是已经下载的大小。
间歇性输出日志，根据已经下载的大小耗时，计算下载速度和剩余时间。
