### ISSUE TITLE
为什么比原有的文件大小，整整大了线程数的倍数？

### ISSUE THREAD

**Issue by FunCodeWorld** [niumoo/down-bit#4]
我开了10个线程，下载下来的文件比真实文件大小，大了10倍，
正好是线程数倍数大小，这是为什么？

**Comment by niumoo** [comment]
确实有这个问题，目前版本已经修复了，去掉了 range 参数末尾的 /* ，当初加这个 /* 也是阅读了 HTTP 请求头的规范写进去的，后来发现某些网站在收到 /* 结尾的 range 参数时，会让 Range 参数失效，导致分段请求失败，所以10个线程的请求都是全部文件内容，大小翻倍。
![image](https://user-images.githubusercontent.com/26371673/94558655-bc25b280-0292-11eb-831f-d3a3c76d0a1f.png)
